#ifndef _pcb_h
#define _pcb_h

#include <ykernel.h>

// Process Control Block datastructure
struct pcb
{
  UserContext uc;
  KernelContext kc;
  pte_t kernel_stack_pages[KERNEL_STACK_MAXSIZE >> PAGESHIFT];
  void* pt_addr;  // address of the corresponding page table
  int pid;        // process id generated by helper_new_pid()
  // int *child_pids;
  // int *parent_pids;
};


typedef struct pcb pcb_t;

#endif