// Contains Process Control Block datastructure
//
// Andrew Chen
// 2/2024

#ifndef _pcb_h
#define _pcb_h

#include <ykernel.h>

struct pcb
{
  UserContext uc;
  KernelContext kc;
  pte_t kernel_stack_pages[KERNEL_STACK_MAXSIZE >> PAGESHIFT];
  void* pt_addr;          // address of the corresponding page table
  int pid;                // process id generated by helper_new_pid()
  int blocked;            // boolean for whether the process is blocked
  int delay_ticks;        // dont switch to this process while delay_ticks > 0, ticks down every clock trap
  void *brk;              // user brk set by Brk syscall
  void *orig_brk;         // initial value of brk
  int *child_pids;        // pids of all children of this process created with Fork()
  int parent_pid;         // pid of the process's parent. If there is no such parent, then the value is -1
  int waited_child_pid;   // pid child process the parent is waiting for. If there is no such child, then the value is -1
};


typedef struct pcb pcb_t;

#endif