// Contains Process Control Block datastructure
//
// Andrew Chen
// 2/2024

#ifndef _pcb_h
#define _pcb_h

#include <ykernel.h>

struct pcb
{
  UserContext uc;
  KernelContext kc;
  pte_t kernel_stack_pages[KERNEL_STACK_MAXSIZE >> PAGESHIFT];
  void* pt_addr;    // address of the corresponding page table
  int pid;          // process id generated by helper_new_pid()
  int blocked;      // boolean for whether the process is blocked
  int delay_ticks;  // dont switch to this process while delay_ticks > 0, ticks down every clock trap
  // int *child_pids;
  // int *parent_pids;
};


typedef struct pcb pcb_t;

#endif